### PR TITLE
Better typings with React.ComponentClass 

### PR DESCRIPTION
**Pull request by minamorl**
identical to #1

### CODE REVIEW

**Comment by patrick91** [comment]
Thank you!

**Comment by patrick91** [comment]
quick question, do you use onClick props (or similar) inside the `styled` css?

**Comment by minamorl** [comment]
What "Inside the styled css" means?
Can you give me some small snippet for explanation?
Maybe no.

**Comment by patrick91** [comment]
Like this:

```
styled.h1`
    color: ${props => props.title === 'x' ? 'red' : 'blue' }
`;
```

I was wondering because it looks like that the onClick (and the others) props were already working as expected before the merge, see:

**Comment by minamorl** [comment]
Not working on my atom-typescript. I found no definition on DefinitelyTyped so it references other sources I guess.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/react/index.d.ts#L76-L81
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/react/index.d.ts#L24-L26

In either case, component-styles seems not returning HTMLFactory directly. It wraps all components by their own class derived from React.Component. See:
https://github.com/styled-components/styled-components/blob/master/src/models/StyledComponent.js

**Comment by patrick91** [comment]
ok! should be ok then :)

**Comment by minamorl** [comment]
btw do you changed type referencing recently? I couldn't import feature/type-def in my project. It worked on your old test branch. Can you repro?

**Comment by patrick91** [comment]
`feature/type-def` doesn't have the built components, so webpack (or what you're using currently) won't be able to find the library, do you want me to push an updated version of the `build/ts` branch?

**Comment by minamorl** [comment]
Oh I see. It's okay I'll use my fork before they merge into master. 
I'm looking forward to seeing they marge your contributions :sparkles:

**Pull request merged**
