### PR TITLE
Better typings with React.ComponentClass

### PR DESCRIPTION
**Pull request by minamorl**
Introduce ComponentClass for using existing React props like `onClick`.

### CODE REVIEW

**Comment by patrick91** [comment]
Thanks! I'll have a look at it later :)

**Comment by patrick91** [comment]
Guess we need this for the native component as well, right?

**Comment by minamorl** [comment]
Yes.
```
const Button = styled.button`
something
`
```
should work as well as native component. e.g.:
```
<Button onClick={}>
```

**Comment by patrick91** [comment]
@minamorl can you please make another PR on the `feature/type-def branch`? I use this one for testing (so it is not clean). I tried to change the base branch but it doesn't work as expected :)

**Comment by minamorl** [comment]
Sure. I'll send PR in a day.
I also found mistakes on SVGElement so I'll send a patch. :p

**Pull request closed without merging**
